{{ if .Values.scheduler.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "topols.fullname" . }}-scheduler-options
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topols.labels" . | nindent 4 }}
data:
  scheduler-options.yaml: |
    listen: "{{ .Values.scheduler.options.listen.host }}:{{ .Values.scheduler.options.listen.port }}"
    {{- if .Values.scheduler.schedulerOptions }}
    {{ toYaml .Values.scheduler.schedulerOptions | indent 4 }}
    {{- end }}
---
{{ end }}
