{{ if and .Values.scheduler.enabled (eq (lower .Values.scheduler.type) "daemonset") }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "topols.fullname" . }}-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topols.labels" . | nindent 4 }}
    {{- with .Values.scheduler.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.scheduler.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  {{- with .Values.scheduler.updateStrategy }}
  updateStrategy: {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: scheduler
      {{ include "topols.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/scheduler/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/component: scheduler
        {{ include "topols.selectorLabels" . | nindent 8 }}
        {{- with .Values.scheduler.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.securityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.scheduler.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "topols.fullname" . }}-scheduler
      containers:
        - name: topols-scheduler
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          command:
            - /topols-scheduler
            - --config=/etc/topols/scheduler-options.yaml
          {{- with .Values.scheduler.args }}
          args: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.env.topols_scheduler }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              host: {{ .Values.scheduler.options.listen.host }}
              port: {{ .Values.scheduler.options.listen.port }}
              path: /status
            {{- with .Values.livenessProbe.topols_scheduler.failureThreshold }}
            failureThreshold: {{ . }}
            {{- end }}
            {{- with .Values.livenessProbe.topols_scheduler.initialDelaySeconds }}
            initialDelaySeconds: {{ . }}
            {{- end }}
            {{- with .Values.livenessProbe.topols_scheduler.timeoutSeconds }}
            timeoutSeconds: {{ . }}
            {{- end }}
            {{- with .Values.livenessProbe.topols_scheduler.periodSeconds }}
            periodSeconds: {{ . }}
            {{- end }}
          readinessProbe:
            httpGet:
              host: {{ .Values.scheduler.options.listen.host }}
              port: {{ .Values.scheduler.options.listen.port }}
              path: /status
          volumeMounts:
            - mountPath: /etc/topols
              name: {{ template "topols.fullname" . }}-scheduler-options
          {{- with .Values.resources.topols_scheduler }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
      hostNetwork: true
      volumes:
        - name: {{ template "topols.fullname" . }}-scheduler-options
          configMap:
            name: {{ template "topols.fullname" . }}-scheduler-options
      {{- with .Values.scheduler.affinity }}
      affinity: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
