{{ if and .Values.scheduler.enabled (eq (lower .Values.scheduler.type) "deployment") }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "topols.fullname" . }}-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topols.labels" . | nindent 4 }}
spec:
  replicas: {{ required ".Values.scheduler.deployment.replicaCount" .Values.scheduler.deployment.replicaCount }}
  {{- with .Values.scheduler.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  {{- with .Values.scheduler.updateStrategy }}
  strategy: {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: topols-scheduler
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/scheduler/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: topols-scheduler
    spec:
      {{- with .Values.securityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.scheduler.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      serviceAccountName: {{ template "topols.fullname" . }}-scheduler
      containers:
        - name: topols-scheduler
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          command:
            - /topols-scheduler
            - --config=/etc/topols/scheduler-options.yaml
          livenessProbe:
            httpGet:
              port: {{ .Values.scheduler.options.listen.port }}
              path: /status
          volumeMounts:
            - mountPath: /etc/topols
              name: {{ template "topols.fullname" . }}-scheduler-options
          {{- with .Values.scheduler.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: {{ template "topols.fullname" . }}-scheduler-options
          configMap:
            name: {{ template "topols.fullname" . }}-scheduler-options
      {{- with .Values.scheduler.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
