{{- if .Values.scheduler.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "topols.fullname" . }}-scheduler
  namespace: {{ .Release.Namespace }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: topols-scheduler
---
{{- end }}
