{{ if .Values.scheduler.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "topols.fullname" . }}-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topols.labels" . | nindent 4 }}
---
{{ end }}
