# permissions for end users to view logicalvolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logicalvolume-viewer-role
rules:
- apiGroups:
  - topols.kvaster.com
  resources:
  - logicalvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - topols.kvaster.com
  resources:
  - logicalvolumes/status
  verbs:
  - get
