apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "topols.fullname" . }}-node
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topols.labels" . | nindent 4 }}
spec:
  {{- with .Values.node.updateStrategy }}
  updateStrategy: {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: node
      {{ include "topols.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: node
        {{ include "topols.selectorLabels" . | nindent 8 }}
      {{- if and .Values.node.metrics.enabled .Values.node.metrics.annotations }}
      annotations: {{ toYaml .Values.node.metrics.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.node.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      serviceAccountName: {{ template "topols.fullname" . }}-node
      {{- with .Values.image.pullSecret}}
      imagePullSecrets:
      - name: {{ . }}
      {{- end }}
      containers:
        - name: topols-node
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          {{- with .Values.node.securityContext }}
          securityContext: {{ toYaml . | nindent 12 }}
          {{- end }}
          command:
            - /topols-node
            - --csi-socket={{ .Values.node.kubeletWorkDirectory }}/plugins/topols.kvaster.com/node/csi-topols.sock
            - --pool-path={{ .Values.node.poolPath }}
          {{- with .Values.node.args }}
          args: {{ toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: healthz
              containerPort: 9808
              protocol: TCP
            - name: metrics
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            failureThreshold: 3
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 60
          {{- with .Values.resources.topols_node }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            {{- if .Values.node.volumeMounts.topolvmNode }}
            {{- toYaml .Values.node.volumeMounts.topolvmNode | nindent 12 }}
            {{- else }}
          - name: node-plugin-dir
            mountPath: {{ .Values.node.kubeletWorkDirectory }}/plugins/topols.kvaster.com/node/
          - name: pool-dir
            mountPath: {{ dir .Values.node.poolPath }}
          - name: pod-volumes-dir
            mountPath: {{ .Values.node.kubeletWorkDirectory }}/pods
            mountPropagation: "Bidirectional"
          - name: csi-plugin-dir
            mountPath: {{ .Values.node.kubeletWorkDirectory }}/plugins/kubernetes.io/csi
            mountPropagation: "Bidirectional"
            {{- end }}

        - name: csi-registrar
          {{- if .Values.image.csi.nodeDriverRegistrar }}
          image: {{ .Values.image.csi.nodeDriverRegistrar }}
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          {{- end }}
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          command:
            - /csi-node-driver-registrar
            - --csi-address={{ .Values.node.kubeletWorkDirectory }}/plugins/topols.kvaster.com/node/csi-topols.sock
            - --kubelet-registration-path={{ .Values.node.kubeletWorkDirectory }}/plugins/topols.kvaster.com/node/csi-topols.sock
            - --http-endpoint=:9809
          ports:
            - containerPort: 9809
              name: healthz
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            failureThreshold: 3
            initialDelaySeconds: 10
            timeoutSeconds: 3
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - rm -rf /registration/topols.kvaster.com /registration/topols.kvaster.com-reg.sock
          {{- with .Values.resources.csi_registrar }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: node-plugin-dir
              mountPath: {{ .Values.node.kubeletWorkDirectory }}/plugins/topols.kvaster.com/node/
            - name: registration-dir
              mountPath: /registration

        - name: liveness-probe
          {{- if .Values.image.csi.livenessProbe }}
          image: {{ .Values.image.csi.livenessProbe }}
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          {{- end }}
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          command:
            - /livenessprobe
            - --csi-address={{ .Values.node.kubeletWorkDirectory }}/plugins/topols.kvaster.com/node/csi-topols.sock
          {{- with .Values.resources.liveness_probe }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: node-plugin-dir
              mountPath: {{ .Values.node.kubeletWorkDirectory }}/plugins/topols.kvaster.com/node/

      volumes:
        {{- if .Values.node.volumes }}
        {{- toYaml .Values.node.volumes | nindent 8 }}
        {{- else }}
      - name: registration-dir
        hostPath:
          path: {{ .Values.node.kubeletWorkDirectory }}/plugins_registry/
          type: Directory
      - name: node-plugin-dir
        hostPath:
          path: {{ .Values.node.kubeletWorkDirectory }}/plugins/topols.kvaster.com/node
          type: DirectoryOrCreate
      - name: csi-plugin-dir
        hostPath:
          path: {{ .Values.node.kubeletWorkDirectory }}/plugins/kubernetes.io/csi
          type: DirectoryOrCreate
      - name: pod-volumes-dir
        hostPath:
          path: {{ .Values.node.kubeletWorkDirectory }}/pods/
          type: DirectoryOrCreate
      - name: pool-dir
        hostPath:
          path: {{ dir .Values.node.poolPath }}
          type: Directory
        {{- end }}

      {{- with .Values.node.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.node.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
