{{- if .Values.podSecurityPolicy.create }}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "topols.fullname" . }}-node
  labels:
    {{- include "topols.labels" . | nindent 4 }}
spec:
  privileged: true
  allowPrivilegeEscalation: true
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'secret'
    - 'hostPath'
  allowedHostPaths:
    {{- if .Values.node.psp.allowedHostPaths }}
    {{- toYaml .Values.node.psp.allowedHostPaths | nindent 4 }}
    {{- else }}
  - pathPrefix: {{ .Values.node.kubeletWorkDirectory }}
    readOnly: false
  - pathPrefix: {{ dir .Values.node.poolPath }}
    readOnly: false
    {{- end }}
  hostNetwork: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: true
---
{{- end }}
