apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}:controller
  labels:
    {{- include "topols.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ template "topols.fullname" . }}-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}:controller
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "topols.clusterRolePrefix" }}-csi-provisioner-role
  labels:
    {{- include "topols.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ template "topols.fullname" . }}-controller
roleRef:
  kind: ClusterRole
  name: {{ template "topols.clusterRolePrefix" }}-external-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "topols.clusterRolePrefix" }}-csi-resizer-role
  labels:
    {{- include "topols.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ template "topols.fullname" . }}-controller
roleRef:
  kind: ClusterRole
  name: {{ template "topols.clusterRolePrefix" }}-external-resizer-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "topols.clusterRolePrefix" }}-csi-snapshotter-role
  labels:
  {{- include "topols.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ template "topols.fullname" . }}-controller
roleRef:
  kind: ClusterRole
  name: {{ template "topols.clusterRolePrefix" }}-external-snapshotter-runner
  apiGroup: rbac.authorization.k8s.io
