apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: topols.kvaster.com
  labels:
    {{- include "topols.labels" . | nindent 4 }}
spec:
  {{- with .Values.controller.storageCapacityTracking.enabled }}
  storageCapacity: true
  {{- end }}
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
