apiVersion: v1
kind: Service
metadata:
  name: {{ template "topols.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topols.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: controller
    {{ include "topols.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: 443
      protocol: TCP
      targetPort: webhook
