on:
  workflow_call:
    inputs:
      topols_version:
        description: "TopoLS version"
        default: "devel"
        type: string
      image_tag:
        description: "Image tag"
        default: "latest"
        type: string
      image_prefix:
        description: "Image prefix"
        default: ""
        type: string
      push:
        description: "Push images"
        default: "false"
        type: string

jobs:
  build-images:
    name: "build-images"
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: true
      matrix:
        image:
          - "normal"
          - "with-sidecar"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        if: ${{ inputs.push == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}
      - run: make multi-platform-image-${{ matrix.image }}
        env:
          TOPOLS_VERSION: ${{ inputs.topols_version }}
          IMAGE_TAG: ${{ inputs.image_tag }}
          IMAGE_PREFIX: ${{ inputs.image_prefix }}
          PUSH: ${{ inputs.push }}
