name: Main
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: cache go dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ hashFiles('go.sum', 'Makefile') }}
          restore-keys: |
            go-
      - run: make setup
      - run: make check-uncommitted
      - run: make test
      #- run: make groupname-test
      - run: make multi-platform-images
