name: Main
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: cache go dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ hashFiles('go.sum', 'Makefile', 'versions.mk') }}
          restore-keys: |
            go-
      - run: make setup
      - run: make check-uncommitted
      - run: make test
      #- run: make groupname-test

  build-images:
    name: "build-images"
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: true
      matrix:
        image:
          - "normal"
          - "with-sidecar"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: make setup-docker-buildx
      - run: make multi-platform-image-${{ matrix.image }}

  container-structure-test:
    name: "container-structure-test"
    needs: build
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: true
      matrix:
        image:
          - "normal"
          - "with-sidecar"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: make install-container-structure-test
      - run: make image-${{ matrix.image }}
      - run: make container-structure-test STRUCTURE_TEST_TARGET=${{ matrix.image }}
